# Generated by Django 3.2.3 on 2021-05-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecsv',
            name='gems',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filecsv',
            name='spent_money',
            field=models.DecimalField(decimal_places=2, default='10', max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filecsv',
            name='username',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
