# Generated by Django 3.2.3 on 2021-05-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210519_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecsv',
            name='gems',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='filecsv',
            name='spent_money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='filecsv',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
