# Generated by Django 3.2.3 on 2021-05-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210519_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecsv',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='csv/'),
        ),
    ]
